/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtsRouteImport } from './routes/ats'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as IdcardRouteImport } from './routes/idcard'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as ApiEnhancePhotoRouteImport } from './routes/api/enhance-photo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsRoute = AtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const IdcardRoute = IdcardRouteImport.update({
  id: '/idcard',
  path: '/idcard',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnhancePhotoRoute = ApiEnhancePhotoRouteImport.update({
  id: '/api/enhance-photo',
  path: '/api/enhance-photo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ats': typeof AtsRoute
  '/chat': typeof ChatRoute
  '/feedback': typeof FeedbackRoute
  '/generate': typeof GenerateRoute
  '/idcard': typeof IdcardRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRoute
  '/api/ai': typeof ApiAiRoute
  '/api/enhance-photo': typeof ApiEnhancePhotoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ats': typeof AtsRoute
  '/chat': typeof ChatRoute
  '/feedback': typeof FeedbackRoute
  '/generate': typeof GenerateRoute
  '/idcard': typeof IdcardRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRoute
  '/api/ai': typeof ApiAiRoute
  '/api/enhance-photo': typeof ApiEnhancePhotoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ats': typeof AtsRoute
  '/chat': typeof ChatRoute
  '/feedback': typeof FeedbackRoute
  '/generate': typeof GenerateRoute
  '/idcard': typeof IdcardRoute
  '/records': typeof RecordsRoute
  '/settings': typeof SettingsRoute
  '/api/ai': typeof ApiAiRoute
  '/api/enhance-photo': typeof ApiEnhancePhotoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ats'
    | '/chat'
    | '/feedback'
    | '/generate'
    | '/idcard'
    | '/records'
    | '/settings'
    | '/api/ai'
    | '/api/enhance-photo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ats'
    | '/chat'
    | '/feedback'
    | '/generate'
    | '/idcard'
    | '/records'
    | '/settings'
    | '/api/ai'
    | '/api/enhance-photo'
  id:
    | '__root__'
    | '/'
    | '/ats'
    | '/chat'
    | '/feedback'
    | '/generate'
    | '/idcard'
    | '/records'
    | '/settings'
    | '/api/ai'
    | '/api/enhance-photo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtsRoute: typeof AtsRoute
  ChatRoute: typeof ChatRoute
  FeedbackRoute: typeof FeedbackRoute
  GenerateRoute: typeof GenerateRoute
  IdcardRoute: typeof IdcardRoute
  RecordsRoute: typeof RecordsRoute
  SettingsRoute: typeof SettingsRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiEnhancePhotoRoute: typeof ApiEnhancePhotoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats': {
      id: '/ats'
      path: '/ats'
      fullPath: '/ats'
      preLoaderRoute: typeof AtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idcard': {
      id: '/idcard'
      path: '/idcard'
      fullPath: '/idcard'
      preLoaderRoute: typeof IdcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enhance-photo': {
      id: '/api/enhance-photo'
      path: '/api/enhance-photo'
      fullPath: '/api/enhance-photo'
      preLoaderRoute: typeof ApiEnhancePhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtsRoute: AtsRoute,
  ChatRoute: ChatRoute,
  FeedbackRoute: FeedbackRoute,
  GenerateRoute: GenerateRoute,
  IdcardRoute: IdcardRoute,
  RecordsRoute: RecordsRoute,
  SettingsRoute: SettingsRoute,
  ApiAiRoute: ApiAiRoute,
  ApiEnhancePhotoRoute: ApiEnhancePhotoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
